name: Playwright Tests

on:
  workflow_dispatch:

#  push:
#    branches: [ main, 18-testy-na-CI ]
#  pull_request:
#    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Force a non-shallow checkout, so that we can reference $GITHUB_BASE_REF.
          # See https://github.com/actions/checkout for more details.
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

#      - name: Install Playwright Browsers
#        run: npx playwright install --with-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps --force

      - name: Start app
        run: npm run start -- --host 0.0.0.0 --port 5173 &

      - name: Wait for app
        run: npx wait-on http://127.0.0.1:5173
        # jeśli nie chcesz dodawać wait-on do projektu, można użyć prostszego sleep,
        # ale wait-on jest stabilniejsze

      - name: Run changed Playwright tests
        run: npx playwright test --only-changed=origin/$GITHUB_BASE_REF
        if: github.event_name == 'pull_request'

      - name: Run Playwright tests
        run: npx playwright test
        if: github.event_name != 'pull_request'
